# Generated by Django 2.0.7 on 2018-08-28 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_exam_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='Date',
            new_name='Date_time',
        ),
    ]
