# Generated by Django 2.0.7 on 2018-08-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Classes', models.CharField(max_length=128)),
                ('Subjects', models.CharField(max_length=128)),
                ('Extras', models.CharField(max_length=120)),
                ('Payments', models.CharField(max_length=120)),
                ('Name', models.CharField(max_length=64)),
            ],
        ),
    ]
