# Generated by Django 2.0.7 on 2018-08-19 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('total', models.IntegerField()),
                ('status', models.CharField(choices=[('0', 'Paid'), ('1', 'Due')], max_length=1)),
                ('method', models.CharField(choices=[('0', 'Cash'), ('1', 'Cheque')], max_length=20)),
                ('date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
