# Generated by Django 2.0.7 on 2018-08-19 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classe', '0001_initial'),
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('r_class', 'section')},
        ),
    ]
