# Generated by Django 2.0.7 on 2018-08-06 20:15

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('calander', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calander',
            name='Date',
            field=models.DateField(default=django.utils.datetime_safe.date.today),
            preserve_default=False,
        ),
    ]
