# Generated by Django 2.0.7 on 2018-07-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sgrade', models.CharField(choices=[('N', 'Nursery'), ('L', 'L.KG.'), ('U', 'U.KG.'), ('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five'), ('6', 'Six'), ('7', 'Seven'), ('8', 'Eight'), ('9', 'Nine'), ('x', 'Ten'), ('xi', 'Eleven'), ('xii', 'Twelve')], max_length=3)),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=128)),
                ('grade', models.CharField(max_length=11)),
                ('section', models.CharField(max_length=3)),
                ('roll_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=128)),
                ('phone_no', models.CharField(max_length=16)),
                ('qualifications', models.CharField(max_length=60)),
            ],
        ),
    ]
