# Generated by Django 2.0.7 on 2018-07-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eis', '0003_auto_20180720_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('G', 'Select One'), ('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=2),
        ),
    ]
