# Generated by Django 2.0.7 on 2018-07-20 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eis', '0004_auto_20180720_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='gender',
            new_name='select_gender',
        ),
    ]
