# Generated by Django 2.0.7 on 2018-07-20 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eis', '0005_auto_20180720_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='sgrade',
            new_name='select_grade',
        ),
        migrations.RenameField(
            model_name='grade',
            old_name='section',
            new_name='select_section',
        ),
    ]
