# Generated by Django 2.0.7 on 2018-07-20 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eis', '0006_auto_20180720_1304'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='teachers',
            new_name='teacher',
        ),
    ]
