# Generated by Django 2.0.7 on 2018-07-30 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('Is_Present', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.CharField(max_length=11)),
                ('Section', models.CharField(max_length=2)),
                ('Capacity', models.IntegerField()),
                ('No_of_Students', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('full_marks', models.IntegerField()),
                ('pass_marks', models.IntegerField()),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduinfosys.classes')),
            ],
        ),
        migrations.CreateModel(
            name='Libraries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book', models.CharField(max_length=254)),
                ('No_of_Books_Total', models.IntegerField()),
                ('No_of_Books_Avilable', models.IntegerField()),
                ('Of_Class', models.CharField(max_length=11)),
                ('Of_Subject', models.CharField(max_length=20)),
                ('Publisher_Name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_Father', models.CharField(max_length=64)),
                ('Name_of_Mother', models.CharField(max_length=64)),
                ('Contacts', models.CharField(max_length=20)),
                ('Address_Permanent', models.CharField(max_length=64)),
                ('Address_Current', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.CharField(max_length=11)),
                ('Section', models.CharField(max_length=2)),
                ('roll_no', models.IntegerField()),
                ('Name', models.CharField(max_length=64)),
                ('Father_name', models.CharField(max_length=64)),
                ('Mother_name', models.CharField(max_length=64)),
                ('Guardians_name', models.CharField(max_length=64)),
                ('Guardians_contact', models.CharField(max_length=64)),
                ('Address_Current', models.CharField(max_length=64)),
                ('Address_Permanent', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
                ('Book', models.CharField(max_length=64)),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduinfosys.classes')),
            ],
        ),
        migrations.CreateModel(
            name='teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Classes', models.CharField(max_length=128)),
                ('Subjects', models.CharField(max_length=128)),
                ('Extras', models.CharField(max_length=120)),
                ('Payments', models.CharField(max_length=120)),
                ('Name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='subjects',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduinfosys.teachers'),
        ),
        migrations.AddField(
            model_name='parents',
            name='Related_Student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduinfosys.students'),
        ),
        migrations.AddField(
            model_name='exams',
            name='Subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduinfosys.Subjects'),
        ),
        migrations.AddField(
            model_name='attendence',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduinfosys.students'),
        ),
    ]
