# Generated by Django 2.0.7 on 2018-08-01 07:18

from django.db import migrations


class Migration(migrations.Migration):

    atomic=False	
    dependencies = [
        ('eduinfosys', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='classes',
            new_name='classe',
        ),
        migrations.RenameModel(
            old_name='Exams',
            new_name='Exam',
        ),
        migrations.RenameModel(
            old_name='Libraries',
            new_name='Librarie',
        ),
        migrations.RenameModel(
            old_name='Parents',
            new_name='Parent',
        ),
        migrations.RenameModel(
            old_name='students',
            new_name='student',
        ),
        migrations.RenameModel(
            old_name='Subjects',
            new_name='Subject',
        ),
        migrations.RenameModel(
            old_name='teachers',
            new_name='teacher',
        ),
    ]
