# Generated by Django 2.0.7 on 2018-08-02 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eduinfosys', '0003_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='r_classe',
            field=models.ForeignKey(db_column='Class', on_delete=django.db.models.deletion.CASCADE, to='eduinfosys.classe'),
        ),
    ]
