# Generated by Django 2.0.7 on 2018-08-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduinfosys', '0004_auto_20180802_0752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='name',
            new_name='section',
        ),
        migrations.RemoveField(
            model_name='section',
            name='r_classe',
        ),
        migrations.AddField(
            model_name='section',
            name='r_class',
            field=models.CharField(default=2131, max_length=11),
            preserve_default=False,
        ),
    ]
