# Generated by Django 2.0.7 on 2018-08-03 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eduinfosys', '0005_auto_20180802_0759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees_paid', models.IntegerField()),
                ('fees_due', models.IntegerField()),
                ('status', models.TextField()),
                ('Date_of_Transaction', models.DateTimeField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduinfosys.student')),
            ],
        ),
    ]
