# Generated by Django 2.0.7 on 2018-08-03 09:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eduinfosys', '0009_auto_20180803_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounting',
            name='Time_of_Transaction',
            field=models.TimeField(default=datetime.datetime(2018, 8, 3, 9, 9, 17, 829034, tzinfo=utc)),
        ),
    ]
