# Generated by Django 2.0.7 on 2018-08-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='noticeboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
                ('Date_Published', models.DateField()),
                ('Details', models.TextField()),
                ('Date_Expiry', models.DateField()),
            ],
        ),
    ]
