# Generated by Django 2.0.7 on 2018-08-20 12:17

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.CharField(max_length=12)),
                ('start_month', models.DateField(max_length=20)),
                ('end_year', models.CharField(max_length=12)),
                ('end_month', models.CharField(max_length=20)),
                ('Active_Deactive', models.CharField(choices=[('A', 'Active'), ('D', 'Deactive')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Caste_Religion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_caste', models.CharField(max_length=30)),
                ('student_relegion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('fax', models.CharField(max_length=20)),
                ('admin_contact_person', models.CharField(max_length=64)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('Institution_code', models.CharField(max_length=5)),
            ],
        ),
    ]
