# Generated by Django 2.0.7 on 2018-08-21 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='country',
        ),
    ]
