# Generated by Django 2.0.7 on 2018-08-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_remove_institution_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='country',
            field=models.CharField(default='Nepal', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
            preserve_default=False,
        ),
    ]
