# Generated by Django 2.0.7 on 2018-08-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_auto_20180822_0904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caste_religion',
            old_name='student_relegion',
            new_name='student_religion',
        ),
        migrations.AlterField(
            model_name='academics',
            name='start_month',
            field=models.CharField(max_length=20),
        ),
    ]
