# Generated by Django 2.0.7 on 2018-08-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('amount', models.IntegerField()),
                ('method', models.CharField(choices=[('0', 'Cash'), ('1', 'Cheque')], max_length=20)),
                ('date', models.DateField()),
            ],
        ),
    ]
