# Generated by Django 2.0.7 on 2018-08-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=64)),
                ('author', models.CharField(max_length=64)),
                ('publisher', models.CharField(max_length=64)),
                ('edition', models.CharField(max_length=64)),
            ],
        ),
    ]
