# Generated by Django 2.0.7 on 2018-08-06 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('section', '0001_initial'),
        ('teacher', '0001_initial'),
        ('subject', '0001_initial'),
        ('classe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time_start', models.TimeField()),
                ('Time_end', models.TimeField()),
                ('Day', models.CharField(choices=[('0', 'Sunday'), ('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday')], max_length=1)),
                ('Date', models.DateField()),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classe.classe')),
                ('Section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.section')),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.Subject')),
                ('Teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
    ]
