# Generated by Django 2.0.7 on 2018-08-19 08:36

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateField()),
                ('batch', models.CharField(max_length=64)),
                ('course', models.CharField(max_length=64)),
                ('academic_year', models.CharField(default='2018-2019', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='hostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel', models.BooleanField()),
                ('hostel_name', models.CharField(max_length=100)),
                ('hostel_address', models.CharField(max_length=200)),
                ('hostel_room', models.CharField(max_length=20)),
                ('reg_date', models.DateField()),
                ('vacation_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_fee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='qualifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_institution', models.CharField(max_length=100)),
                ('address_of_the_institution', models.TextField()),
                ('qualifications', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField()),
                ('Name', models.CharField(max_length=64)),
                ('Father_name', models.CharField(max_length=64)),
                ('Mother_name', models.CharField(max_length=64)),
                ('Guardians_name', models.CharField(max_length=64)),
                ('Guardians_contact', models.CharField(max_length=64)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('Address_current', models.CharField(max_length=64)),
                ('Address_permanent', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=64)),
                ('mobile', models.CharField(max_length=20)),
                ('Section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.section')),
            ],
        ),
        migrations.AddField(
            model_name='admission',
            name='qualifications',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.qualifications'),
        ),
        migrations.AddField(
            model_name='admission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('Section', 'roll_no')},
        ),
    ]
