# Generated by Django 2.0.7 on 2018-08-19 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Section',
            new_name='Section_Class',
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('Section_Class', 'roll_no')},
        ),
    ]
