# Generated by Django 2.0.7 on 2018-08-06 20:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees_paid', models.IntegerField()),
                ('fees_due', models.IntegerField()),
                ('status', models.TextField()),
                ('Date_of_Transaction', models.DateField()),
                ('Time_of_Transaction', models.TimeField(default=datetime.datetime(2018, 8, 6, 20, 10, 9, 997612, tzinfo=utc))),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
