# Generated by Django 2.0.7 on 2018-08-19 08:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='accounting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees_paid', models.IntegerField()),
                ('status', models.TextField()),
                ('Date_of_Transaction', models.DateField()),
                ('Time_of_Transaction', models.TimeField(default=datetime.datetime(2018, 8, 19, 8, 36, 20, 486107, tzinfo=utc))),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
