# Generated by Django 2.0.7 on 2018-08-06 20:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20180806_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounting',
            name='Time_of_Transaction',
            field=models.TimeField(default=datetime.datetime(2018, 8, 6, 20, 20, 34, 612311, tzinfo=utc)),
        ),
    ]
