# Generated by Django 2.0.7 on 2018-08-19 09:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20180819_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounting',
            name='Time_of_Transaction',
            field=models.TimeField(default=datetime.datetime(2018, 8, 19, 9, 6, 10, 133601, tzinfo=utc)),
        ),
    ]
