# Generated by Django 2.0.7 on 2018-08-20 07:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20180819_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounting',
            name='Time_of_Transaction',
            field=models.TimeField(default=datetime.datetime(2018, 8, 20, 7, 27, 35, 175647, tzinfo=utc)),
        ),
    ]
