# Generated by Django 2.0.7 on 2018-08-20 09:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_auto_20180820_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounting',
            name='Time_of_Transaction',
            field=models.TimeField(default=datetime.datetime(2018, 8, 20, 9, 8, 56, 683552, tzinfo=utc)),
        ),
    ]
