# Generated by Django 2.0.7 on 2018-08-20 11:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_auto_20180820_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounting',
            name='Time_of_Transaction',
            field=models.TimeField(default=datetime.datetime(2018, 8, 20, 11, 20, 5, 874697, tzinfo=utc)),
        ),
    ]
