# Generated by Django 2.0.7 on 2018-08-20 12:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_auto_20180820_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounting',
            name='Time_of_Transaction',
            field=models.TimeField(default=datetime.datetime(2018, 8, 20, 12, 17, 31, 707932, tzinfo=utc)),
        ),
    ]
