# Generated by Django 2.0.7 on 2018-08-22 09:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_auto_20180821_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounting',
            name='Time_of_Transaction',
            field=models.TimeField(default=datetime.datetime(2018, 8, 22, 9, 4, 5, 308562, tzinfo=utc)),
        ),
    ]
