# Generated by Django 2.0.7 on 2018-08-27 08:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_auto_20180822_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounting',
            name='Time_of_Transaction',
            field=models.TimeField(default=datetime.datetime(2018, 8, 27, 8, 52, 27, 694041, tzinfo=utc)),
        ),
    ]
